export const EnumUserRole = Object.freeze({
  ROLE_ADMIN: 'ADMIN',
  ROLE_MANAGER: 'MANAGER',
  ROLE_CASHIER: 'CASHIER',
  ROLE_RECEPTION: 'RECEPTION',
  ROLE_TECHNICAL: 'TECHNICAL',
  ROLE_WAREHOUSE: 'WAREHOUSE',
})
